function [BW,maskedImage] = segmentImageFinal(RGB,MASK)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 18-Mar-2022
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Load Mask
BW = MASK;

% Erode mask with disk
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Close mask with rectangle
dimensions = [17 3];
se = strel('rectangle', dimensions);
BW = imclose(BW, se);

% Erode mask with line
length = 5.000000;
angle = 0.000000;
se = strel('line', length, angle);
BW = imerode(BW, se);

% Erode mask with octagon
radius = 0;
se = strel('octagon', radius);
BW = imerode(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

