% Auto-generated by cameraCalibrator app on 04-Mar-2022
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/Users/jacek/Documents/MATLAB/TWM/IMG1.jpg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5578.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5577.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5576.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5574.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5573.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5572.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5571.jpeg',...
    '/Users/jacek/Documents/MATLAB/TWM/IMG_5570.jpeg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 200;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
